---
title: "Data Reformating"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, message=FALSE}
# Packages for the data manipulation
library(dplyr)
library(tidyr)

# to call stats filter -stats::filter()
```


# Reformat Catch Data 

* Remove the "all" column
* Create the species column
    - move from wide to long
* General QA

[Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). urn:node:GOA. df35b.304.2. ](https://knb.ecoinformatics.org/view/df35b.304.2)

```{r}
catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"), stringsAsFactors=FALSE)

head(catch_original)
```


Remove the `all` and `notesRegCode` columns using `select`

Cmd +shift + m : pipe operator shortcut %>%

```{r}
# or select(-All, -notesRegCode)
catch_long <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% # select only these
  gather(key = "species",value = "catch",Chinook, Sockeye, Coho, Pink, Chum) # or you can do gather(key = "species",value = "catch", -Region, -Year) implying gather except for Region and Year


head(catch_long)
```


```{r}
catch_wide <- catch_long %>%
  spread(key = species, value = catch)

head(catch_wide)
```
# Join the Region Definitions



#  Misc. Functions

